# Generated by Django 5.0 on 2024-01-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzy_app', '0002_alter_post_dislikes_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
