# Generated by Django 5.0 on 2024-01-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzy_app', '0005_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
