# Generated by Django 5.0 on 2024-01-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzy_app', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
